version: '3.8'

x-base_service: &base_service
  volumes:
    - ./data:/data
    - ./output:/output
  stop_signal: SIGKILL
  tty: true
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            device_ids: ['0']
            capabilities: [compute, utility]

name: webui-docker

services:
  download:
    build: ./services/download/
    profiles: ["download"]
    volumes:
      - ./data:/data

  auto:
    <<: *base_service
    profiles: ["auto", "combined"]
    build: ./services/AUTOMATIC1111
    image: sd-auto:78
    environment:
      - CLI_ARGS=--allow-code --medvram --xformers --enable-insecure-extension-access --api
    ports:
      - "7860:7860"

  auto-cpu:
    <<: *base_service
    profiles: ["auto-cpu"]
    build: ./services/AUTOMATIC1111
    image: sd-auto:78
    environment:
      - CLI_ARGS=--no-half --precision full --allow-code --enable-insecure-extension-access --api
    deploy: {}

  comfy:
    <<: *base_service
    profiles: ["comfy", "combined"]
    build: ./services/comfy/
    image: sd-comfy:7
    environment:
      - CLI_ARGS=--disable-cuda-malloc
    ports:
      - "7861:7860"

  comfy-cpu:
    <<: *base_service
    profiles: ["comfy-cpu"]
    build: ./services/comfy/
    image: sd-comfy:7
    environment:
      - CLI_ARGS=--cpu
    deploy: {}
    